### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by tgobira** [edubart/otclient#773]
Hi there fellas.

I'm trying to compile the project on VISUAL STUDIO 2015 and even iputing  Include and Library VC++ Directories with bin information (where is located glew32.lib and other files), when I try to compile the project, I receive the error below.

**Error	LNK1181	cannot open input file 'glew32.lib'	otclient	C:\OT\otclient-master\vc12\LINK	1**	

I've followed the tutorial in the page informing where to configure Library (C/C++) and Includes (Linker), and still have the same problem.

Anyone had the same issue?

**Comment by pvpfleczu** [comment]
Show your Property Page- **VC++ Directories.**

**Comment by tgobira** [comment]
I've downloaded another lib package and configured Library and Includes and then i've passed this part. Now I'm stuck with a boost part that needs to be downloaded and then configured on VC++ Diretories.

Does anyone have the link to download boost dll's?

**Comment by pvpfleczu** [comment]
http://www.mediafire.com/file/85tymxnox5wqr4k/otclient-msvc13-libs+%281%29.zip

All what you need.

**Comment by tgobira** [comment]
I already had downloaded this package. Now i need the boost_1_57_0. I've found the website but don't know how to "install" it and then use its components.

Thankx for helpin me out.

**Comment by A-Syntax** [comment]
@pvpfleczu why such a huge file? 29.5 megs?

This is what I compile with & and its only 3.2 megs
http://www.mediafire.com/file/vip38k1uy7eagk0/otclient-msvc13-libs.zip

**Comment by tgobira** [comment]
@A-Syntax Ty vm... There is any tutorial to install it our just decompress in a folder then configure links inside VS2015?

I'll try to compile now...

**Comment by tgobira** [comment]
Stuck with this errors now:

Error	LNK2001	unresolved external symbol __imp__glewInit	otclient	C:\OT\otclient-master\vc12\graphics.obj	1	
Error	LNK2001	unresolved external symbol __imp__glewGetErrorString	otclient	C:\OT\otclient-master\vc12\graphics.obj	1	
Error	LNK1120	2 unresolved externals	otclient	C:\OT\otclient-master\vc12\Release\otclient.exe	1	

Does anyone have seen something like it?

Ty VM!

**Comment by tgobira** [comment]
This problem got solved with upper help!
