### ISSUE TITLE
Buildin on Mac error 'AL/al.h' file not found

### ISSUE THREAD

**Issue by llmdev** [edubart/otclient#1058]
Lib not found on compule, 'AL/al.h' file not found

**Comment by diath** [comment]
It looks like the Mac OS article on the wiki does not mention OpenAL as a dependency, does the following help?
`brew install openal-soft`

**Comment by llmdev** [comment]
does not solve the problem, installed openal-soft and still the same error

**Comment by llmdev** [comment]
`CMake Warning (dev) at src/framework/CMakeLists.txt:152 (set):
  implicitly converting 'Git commit string (intended for releases)' to
  'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/framework/CMakeLists.txt:153 (set):
  implicitly converting 'Git revision string (intended for releases)' to
  'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Link to static libraries: OFF
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- LuaJIT: OFF
-- Debug information: ON
-- Crash handler: OFF
CMake Warning (dev) at src/framework/CMakeLists.txt:290 (set):
  implicitly converting 'Use OpenGL ES 1.0 or 2.0 (for mobiles devices)' to
  'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- OpenGL ES: OFF
-- Bot protection: ON
-- Use precompiled header: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lucasmoura/Desktop/otclient/build
[  0%] Building CXX object CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o
[  1%] Building CXX object CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o
[  2%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/asyncdispatcher.cpp.o
[  3%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/binarytree.cpp.o
In file included from /Users/lucasmoura/Desktop/otclient/src/framework/luafunctions.cpp:38:
In file included from /Users/lucasmoura/Desktop/otclient/src/framework/../framework/sound/soundmanager.h:26:
/Users/lucasmoura/Desktop/otclient/src/framework/../framework/sound/declarations.h:30:10: fatal error:
      'AL/al.h' file not found
#include <AL/al.h>
         ^~~~~~~~~
/Users/lucasmoura/Desktop/otclient/src/framework/util/crypt.cpp:35:10: fatal error:
      'openssl/rsa.h' file not found
#include <openssl/rsa.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o] Error 1
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
make: *** [all] Error 2
`


output

**Comment by RafaeLeal** [comment]
I was having this problem, but I managed to compile it and run with this change:
```diff
-#include <AL/al.h>
-#include <AL/alc.h>
+#include <OpenAL/al.h>
+#include <OpenAL/alc.h>
```

Unfortunally I wasn't able to connect to my server, but I think its unrelated :P

**Comment by vavepl** [comment]
> I was having this problem, but I managed to compile it and run with this change:
> 
> ```diff
> -#include <AL/al.h>
> -#include <AL/alc.h>
> +#include <OpenAL/al.h>
> +#include <OpenAL/alc.h>
> ```
> 
> I'm not sure if this change would be compatible with other platforms, I guess not..?
> 
> Unfortunally I wasn't able to connect to my server, but I think its unrelated :P

works on macos catalina 10.15.7

**Comment by marmichalski** [comment]
This will be resolved by #1133, if accepted 😎

**Comment by nightshining** [comment]
FYI Still seeing this issue on Mac OS 13.0.1 (22A400) with latest Brew install and OpenAL.  

#include <OpenAL/al.h>
#include <OpenAL/alc.h>

fixed the issue
