### ISSUE TITLE
Compatibility with lua 5.2

### ISSUE THREAD

**Issue by assassina** [edubart/otclient#430]
I've just tried to compile otclient at fedora 20 and after some work trying to findout all the missing packages (the wiki doesn't have a tutorial for fedora), I've got this error (sorry, but I have no idea how fix the format in here):

[ 17%] Building CXX object CMakeFiles/otclient.dir/src/framework/luaengine/luainterface.cpp.o
/home/fedora20user/otclient/otclient/src/framework/luaengine/luainterface.cpp: In member function ‘void LuaInterface::getEnv(int)’:
/home/fedora20user/otclient/otclient/src/framework/luaengine/luainterface.cpp:897:25: error: ‘lua_getfenv’ was not declared in this scope
     lua_getfenv(L, index);
                         ^
/home/fedora20user/otclient/otclient/src/framework/luaengine/luainterface.cpp: In member function ‘void LuaInterface::setEnv(int)’:
/home/fedora20user/otclient/otclient/src/framework/luaengine/luainterface.cpp:903:25: error: ‘lua_setfenv’ was not declared in this scope
     lua_setfenv(L, index);
                         ^
make[2]: *\* [CMakeFiles/otclient.dir/src/framework/luaengine/luainterface.cpp.o] Erro 1
make[1]: *\* [CMakeFiles/otc

The issue is caused by the fact that lua_setfenv and lua_getfenv have been removed from Lua 5.2. Most debian distributions have the option to install lua 5.1 instead of 5.2, but not Fedora. So, my request is to make otclient work with lua 5.2 (it will have to be done, soon or later).

Cheers, [and with apologies for this cold murder of the English Language]

PS: I've written down all required libraries to install in Fedora, as I was planning to write a tutorial for Fedora. Ofc, that would be useless while otclient doesn't work with lua 5.2 (unless that you can think of a workaround).

Assassina Mutante.
