### PR TITLE
OpenSSL >= 1.1.0 compatibility

### PR DESCRIPTION
**Pull request by divinity76**
OpenSSL did some otclient-breaking changes around 1.1.0, 
this patch should work on both < and >= 1.1.0

- **warning**: UNTESTED as of writing. this fixes the compilation errors, but since i only work on tibia 7.6 (which doesn't use encryption, encryption was implemented in tibia 7.7), i haven't actually tested this patch, should probably get someone to test it before pulling it upstream.

### CODE REVIEW

**Comment by iryont** [comment]
I haven't checked whether the code works either, but I did fix the code style to fit OTClient one.

I do not have OpenSSL >= 1.1.0 myself, so I cannot really merge this branch before someone tests it and confirms it's good to go.

File: src/framework/util/crypt.cpp [hunk 1]
```diff
@@ -327,60 +327,45 @@ void Crypt::rsaGenerateKey(int bits, int e)
...
 #else
-	{
-		BIGNUM *bn=NULL;
-		BIGNUM *be=NULL;
-		BN_dec2bn(&bn, n.c_str());
-		BN_dec2bn(&be, e.c_str());
-		RSA_set0_key(m_rsa,bn,be,NULL);
-		// note, not supposed to free bn/be here, that's m_rsa's destructor's job
-	}
+    BIGNUM *bn, *be;
```
Comment (divinity76) [inline src/framework/util/crypt.cpp]: error: bn and be is not guaranteed by c++ specs to be null-initialized here, and if they're not, the BN_dec2bn() call below will try to read arbitrary memory and UB ensues (most likely it would crash for trying to read uninitialized memory, but it could do other stuff too, if they accidentally pointed to a valid allocated memory location)

- compilers *MAY* null-initialize these variables just for the heck of it, but the c++ specs does not guarantee it, AND null-initializing memory *DOES* incur a runtime performance hit, so a compiler that is instructed to optimize the run-time code for speed should not do it...

the code should be ```BIGNUM *bn=nullptr, *be=nullptr;```  or something like that.

Comment (iryont) [reply src/framework/util/crypt.cpp]: It appears that BN_dec2bn does in fact re-use memory if it's already initialized. I thought it doesn't and it just creates a new BIGNUM instead, so yea, default value of nullptr is required.

Comment (divinity76) [reply src/framework/util/crypt.cpp]: that looks safer, thanks :)

**Comment by alvelvis** [comment]
HI!
I had been struggling to compile because of the OpenSSL 1.1.x problem, so I downloaded divinity76:patch-2 branch and it compiled after a small problem: in the end it printed an error and asked me to recompile with -fPIC parameter. After following instruction in #928. it compiled just fine. Thank you! ;) Any further information you might want to know about the process please just let me know (and how to retrieve it). I've been using OTC in a 8.60 OT serv, Ubuntu 18.04.

**Comment by iryont** [comment]
Lovely :) In such case I will assume it is working properly and I will merge it. Thank you.
